language: ruby
rvm:
  - 2.4.2

sudo: false
addons:
  apt:
    sources:
      - chef-current-precise
    packages:
      - chefdk

before_script:
  # Ensure we make ChefDK's Ruby the default
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/cookstyle --version
  - /opt/chefdk/embedded/bin/foodcritic --version
script:
  - /opt/chefdk/embedded/bin/cookstyle
  - /opt/chefdk/embedded/bin/foodcritic .
  - /opt/chefdk/embedded/bin/rspec
  - /opt/chefdk/embedded/bin/kitchen verify
  - KITCHEN_LOCAL_YAML=.kitchen.dokken.yml /opt/chefdk/embedded/bin/kitchen verify default-ubuntu-1604
matrix:
  fast_finish: true
